apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: argocd.sputinik.tech
        service: https://traefik.kube-system.svc.cluster.local
        originRequest:
          noTLSVerify: true
      - hostname: headlamp.sputinik.tech
        service: https://traefik.kube-system.svc.cluster.local
        originRequest:
          noTLSVerify: true
      - service: http_status:404
