apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudflared-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: token
      remoteRef:
        key: secret/cloudflare
        property: TUNNEL_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
