apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: git@github.com:Spuntininki/homelab-infra.git
    targetRevision: HEAD
    path: apps/platform/infisical/secrets
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: infisical
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
