apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets
  - cert-manager
  - external-secrets
  - vault-integration/application.yaml
  - headlamp
  - argocd-ingress/application.yaml
  - cloudflared/application.yaml
