---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-postgresql
  namespace: infisical
spec:
  encryptedData:
    password: AgAf/jzKGf5OW+nVd5bEA/LNL06dID2sACMzlLm5A0rM8YKjv6q9mo03S2/WN1Z857aveHRMOO6Gl1GTSwyXl352081MMq+wRlcQuJ6xJTGW3FuGvd76ZXIhesLqYyCp+FlgyKkwOkruW7kJ89OzTfhAzNL1ZkBSu5tR37K9rgtIq+5kh5cAm4zI3AoDe9yjAj/xKcyPK+SCSv2YprA0X+JNXjyE61y3iEyBHkFjFe2nmBUrh0BmiwWZo1BMRlyPmdoZzMd7HPLUaa2bKCctAdCm9SjODS59r6ehC9WpnsYjGrSScC8lr9zfvBDzoVIra6TODKPmjbAQ+GE8dqIgfzgYMNietItmM3L8fJ5rdzoRiDO8sGqjgfp1ehCPdj8k7mqzXZUoTr9e3Z4ybtzYv9B1IDhR3kh4zp9/JwyeKREtX6pc0wW1ER+rYJGxj48Zna/ZU+fnbW+MoXQStaIYyFOKs8sw2zycwvDDUj8+2ezl47NYTTQI1XHmsDEebvf0QRT4dVHHAqoc9NYqz49iI9PTVaimv+7seknHeEKozKfUes8Z4KHllWISdq6Xd8urd34XKxJXlTX8GK6osf1ZKP6Vu2mybTZDh2UxZk/W/M/TIwB1w/sDwtQ36+SmkeESdH54XzKLTQSviOp4RSwlRuh8ju5uheyvccAiPu8123yJjwp8hnK/792qERByacq/+DfevstN5qNrzhIGTSKVigzrieFVmWnykpTulwwiloExUw==
    postgres-password: AgCViDpxW/11ItdSRQrUajk3imgf3+u5vMlwtyaEG2K1qMxAYIVcD3kyajmOwuzsoZ5v8VCd+CZgBZkBXhUS9SqSPDH+PZ7Qf145S1MywBLYx1yxyTHkZ1FrE+DmpkY7hGGYWf1dKnMC5rHTSoKtr0NTFnNa0+5Sbopm6QAM25TMGZZuse6Ut7dl1gsCRhGHpfETK/xXHG7Rq9BFjaM6PNFQP+EqNqH96j2JcFDPvTSZsi1cCaa569dHjlnDlihkylpmY3KMyfdlaXwIosUmQl4y6U+J4eWP0UY8s8KloTTy3p5o1FCRBjZvMx0d4UVPlP8LRF1u9nRcxXV1zSvqtWvI7ciYYWtXnA0acgLhISFmjtI3XxXvwHI52VHiVqpQf/yilX5VLYP0EMYePMD3SvxfUY9Flu28MzwHXizXCl7VzcC3pw/1ms3RsELnJY63a+UjbV4DoE4NAzXC5c7vlLtEHRs2Wy2jdEpW0lCAwqEcgipELbS+iM0WtOphjnEJvPCE7o0PYprDs5+6RpGhB5N4XfefR2292LpH6EXljdbaX8vIOM1Nzi2VEtpCRky1+3KHPFYTdzXtJu8JD5KhfgBgWn4MUXsSVr9W5+Q8zIH0x78RmiZiY9dpMo7MmTQXoghxifDYD6Zadz+R7UCJ+Iz6nNO2bmXmD0jP0wko/84fYnIiWVyaxXBJz+PEPNWReZTrvTq/U5nkBDzUqIbgIpHT6dGRlZSV/LcAuv8om2ScUA==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-postgresql
      namespace: infisical
    type: Opaque
