---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-postgresql
  namespace: infisical
spec:
  encryptedData:
    password: AgCszETSXkaM0gjNKEmK6DaCzTGhIkl1z449QktpbewU/flJfZY+J0pCqpMHbijXhJXbwuTTJ1tdk37IJp/RDYR9+zMc6bFnO/VN/IehOSfur92rZRLQ8kM9k7IQrKCHNyRglo7LQyT1LExhFH5+WevKQCpkvznNPu3ro7f/nnUox1OcviPncqx1va7lyWXfCbx3+b51FD38j9uJL0RKedRtBrNJj9skt5+4hweZNCSK/te7ipwy+0N6YgvCYicNVhL2gpxHxPrmuI2qAYzZuxmaDfMQMVriF+B8KJMnoXNq6TCAuMJlSIBxKgjiG/5TiRHulqTLdqdhXihrYE0oxz024J9jd2gYEwhwB9J8SHCXzkXsx7WWzOuOYA8QmpKjpVojdLqmJfn1ml70M/Ps6SHO/MqxLo+/8sfCgWmCMy9erFjIBVtI/fx2JIqfc1O3CHvNyVVEBVdKI5gofOJPk4bx0r+bJHFT2N2ifJ/bC9BB2RzgYT+Fag1PlICEG3fsU8pt/z2sqbsThoitnHpwp/t8h9QnPEF2qc1b7evm6Y5yFPb7CBGeT/bwKKsn7OxnIyJempbQO9yb09rXSjuc4EXSnhWBXMsvhyLxqTQQpZJFydEmAbsypT9qTw6YVf8oLEtZM7MjBmOdr7UtS7o9WK754Kt6z6uGUk5Avc5/MhOswmSLlIK+8laebKiFF4rSFJODLORwF5dy5z+1jL4WxSoj3AsvTkzyPHZGmj8bXF0VFQ==
    postgres-password: AgCeiedEJoQItzm4CC5gcMWe90T2stu9hxFhD2wuq4w1fTe7i8XeqWNekQniv2TFQBZ1thqPl0zv2BGufSieUCJnRSaK9E8rmtClgM00ddztWeyunRRzxuOQby3tZSdXb6S9QHKv7xi8WutCEQ4wUFI7NQwxUcLn6XGGcSVnzyw2VPNJN14J4qjTtcjfnnw4djBNUazjJpEFb3uNejMp2EZplS0tGKFk4V/4haOZPUY0W87nSe0EdyZT3FaMbZ6Hu8deefX/QhaywwapK6BhHlrLu//h5hNmilBw+ZUlibYzZxVXF5QityAncuv6biX0Yi6BqrFSAlM8GvHEAlAciYBd1rQBZ1QbTKRBU4gBwRYbBd+fUjRdcu+JVYo4e7VI7+z1B1cUgxzR5sl3qmtI2i0wIHVKEvpEkPY3SnkYEybKtgoGfIRwyJA/HrOgbrA28pSG4XGc+GBl0U1Yp3Dg7C54+JVbqXfNrpTeqcvTUWSAuNVhFGxd4OyYyoHTu/Wc/qFQ6ZikFSmExagy2hgalR2SA0EVW8T8AIPOlwsU+HgYxDFCzNIAB/dQo2A/BEWOWIy9/iG33UrmLAqYhWbu+mqOnsFQonlPo+a1RIJKklLy4+RNVlm7LVlZTzmms3dnHgR+fc6mAAZKHSXnTGkoqvtJ6JokOH96hC8nVIEMYJzV5e14W0R5JcgsDTqJXMZqdb5ce0NYEgUjDtmLYLHayJbE5ID/wTuvB2i/VCBEwWcOoQ==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-postgresql
      namespace: infisical
    type: Opaque
