---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-postgresql
  namespace: infisical
spec:
  encryptedData:
    password: AgBeTFoLyjVQOV9CJMAyYB5e58WG0Up3ylu/+JjH+xVaKlvoOfaL4wOJRV4DvtXjd0KTQOnZyOs5l8C/N/Xhe2/Z2f7N6mSMMdCj04MGZza8BrlH76CVOOD+QsF/vMRiIZFtTWwpCNMU4Q1d1cfaLFtpmnEOUdAZT3KruPfAjR1danhDAcBJcRnSG/ZcKoN1K6uBMmtxPmH+42fOOxSSrpvNbmAxw144XQcUvdMxh8l+EZFQFW470HOUbQiIvib0BF0Sg2o6cVnA3th4PvkOl9CX2YZw6V3im8Prku3woweijczhpBaX3y37n+NO4FCnQUNEH/HyITtZjfIzt3qwhDO+McD7eBexVImip+PuYdzEsMEYUQos9fxd7xUwiw7CmjBDfuGoKDXcEIJi7vMG1CmG6wQLA36mZgUS8iK7+XJr8bJqLkgkFFCSWAYqWPlJ1Qf6XjgPgLNfvQIqyvyN7CcIIiAk17guybwETBHYFv0DCrxJiP4keqkbWFOK6zEJGJweEK5SdGodb03MMfShGWqpU7Mm6175NyzY3xT4q17geuDuRlynd21f61MLeqgYnA4thRqQJsPKRpqGANq6CNf1uZQ3DOJrgGDRvts08PbnR1/1BKSzJsEfh0aqs59Xv7xnO2Hy/X98HcT28IGcVat61CC3YUCy9CC2kAV5fYAme7Zbgh5bKSKwHqYVkq2YlAb0A84aCXC/pNZ4t3AwOGz4pQ==
    postgres-password: AgAHNSOGbf1z9NwQYTX67muR1QzbGOIWKVool82PzXeU2kbslQnwX9yXXsGfEhWlwT3gJM5nwmlmA+7q1zCUTJE+wDBN8hDpCwNkLizMmB/swU8OKWoru9xFXg7OYWGq5sm0RVlwt4bD2oJWOGP6SZUtvFaLGlZBxWXpyJX+kqg/VkxPDBS/NHFZNygEdSsKsZjXQ2NtQU1ERhcyrJ48BJxpVH6ECgAltOauJYW6HIqmkPLCRMzufxg6vSvnWifBJgBpXcjDOvafd+VgcmCK5ZZ6z9cbhxicPgG4RptcEACSEc44LruDk0iHuy+qcBs4lDq1qcNUFkTyEbYQSRQtERiU6j/dgnOq1i+eS8IrClB7W0kNTHI/kd87W1Qtg8OC4bHaG8VOfFDDGAVPyosieyX5tu40Q90gaUU6QhW9rGRD1J4MwGNN547XDnA852qSEkRgpwnZRsCA+5+bf6UP05iwTKZ42JTOYgJBPXRkI8wFAAG1JAvnXmxWuytwZlNALRPHTonGYmjcNnCG52tZddMiBr5HXSGj7FJv1jxOD5/WsxVkz10+jCMIB6dx+wAldqjxjJCP3bZbdSVmJwnbLciWPKQ7nLCNvvZ6I3AWDanJ6qpm015I/aMhRln8GzXdBs5PBlO0/jBiL1/WYV7EHILJ3RT7X0JmVffWi1pBT5nQkke5F9jfpAHAXAmVMUDBd22RXV4kQeVYNkg58rhT
  template:
    metadata:
      creationTimestamp: null
      name: infisical-postgresql
      namespace: infisical
    type: Opaque
