---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-redis
  namespace: infisical
spec:
  encryptedData:
    redis-password: AgBlZglNO17IOtA6GylEW6LrkSNzRaX8cAkliY2gELXy4DQg7KMEQDmGzjsFiWbs3iM4n2PQys9VwXOIK+zlZbIMcbZOlg+JK/rblkPUdpzBwc3tbvmzIZOp+EynqFibgEA2pCv38cYETU/spSS7UItvcomojcQOdlIeKdr8hbNxfDBsrYnkFfcYOLD+BKmH28WgNJxou2JDSStkCvmbv+29hq9Hxp9JhXDUbOXpyycduei3qPWyIQ6+C4jAqr8GqGT2KcehDVnxTeEF217YgvoDdXSZ8LwOep0RWXrjGd6C0Vu7JlkaHYTABzZboKyfcLiO9wyPWKMNVD4xwKFGgEW7B8Mj2hpSdIog5xG4Fe49mMtecsA0+i/+Y23fzdb3BcTSNkvjgAV/28Sz8imVWNAoT7JGcHMSusqPMbONyASDWdr9x3IpvXreP5CDlkPwg6xbJjPIlNDSiIAXv6tKmXRxnm7tMm4Nmm2eLyqfzZwEafeIzO6rDOvJsNLre6I2GIXOcVjaGXS0FAAC+51odbylQ0edtR9fDOExxpjo9810544ptmrWyjk9ReBBTNEubShC/O5fJmyha3jpmK5/35tEMHrqEP64DgfO28rNofUA817RTnPM6H8jtU6u4EBz5lbaXKONdMFfFYrXO6bzOgruVDIA2eBSpR4BF9H3uy0U1PRUaC3ZhoaS/GTYHnSvWASq/EMVNOKU9+atooxibkcOy5OynKXBUUy0ORXtCQuYyw==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-redis
      namespace: infisical
    type: Opaque
