---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-redis
  namespace: infisical
spec:
  encryptedData:
    redis-password: AgDCbQRiedpfQ62h9+aS4MPt5N58gS5K+Y8CoPpacPHx34UV6XiLEVLt11mLze23ZQgJ822AXujjNQIQpI4YM3/HUY0X8wNEMCbvWoJ39/rYNGgrKjRqRsUFdviRztJOLSmHdVHPreJCoDr634LD3oMz2a39xDFEC7aOZiBN8xxNoeaTzkGbhP5qXOU5pi6pnCYuA3HiaaOJHX11uGzezSx2TAi3IDqjb73bceA92it2UCwqN6y8Mjk610bW8nuTdMbHiFwOiq39OErQ0+86SQNHNC8nQyjjpyTn1lq+YGqtmUJ0jurCJlT7lkO11prENC1+JLU5l4S0D0i0TCIx6ahyIcNhyD8+4gikHtc02lhzgZDME/AZqoQs7eS3GmJukSdGKn+OFS/1P5PTdq6eHWohqN/oZNTsfiD/6khxXKVaEBfFq0ivVZlLD4XetQ35rK1pbixtWIdW8vEahvKx2bUdBjEQnnZ3+zzb8p21INBPgtYFeLU4nnJNjmwnRVTkxLh88GE5Z6iezkXfFWdCooU9SS9q4CIbQgzs4wBI+ciKCjemTxA5VvkvuQ3v28hbDM+N5HCjyPEIUQdY3oaqzQPNMY9p3XNjYxNVXXi9tAAy8czOWXBG6Qx9CJTdCVPD7aADU02ncEQ6x9xlh1ZKH2O189TqRiHvKM9FWO9ImiV1XhI2QJu8qfGfllTJD78Z58H/9Nw6ZWckeZ0XMMjcOlhJwlxcyUFORgfEEtprFc5VLw==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-redis
      namespace: infisical
    type: Opaque
