---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-redis
  namespace: infisical
spec:
  encryptedData:
    redis-password: AgChndN8XYrX5VZMPUliiFATLhvQuN3JYhwBgipuV06ra7/qPb/fdwk/TPqbnUIU1431Sn+Bt3tQJIkfLDwk815FIPbUggAThjEnia7CtDJ3oG7AXYgDp7Q8ZGiQ4R0uaX0IgMMAagNYgJ7tOQ8E6W4nbwMYiBOpI3DnfUOj83tHPPqR2AInCvOf/TGY6zOTNYTKe40K8cJGWeZiYzhF7u5d/PE4FhhB7mCrCKJO6KJiV5qts9GqsO2AcbD5EMe1skc+SvsA9Ki3KvZVwOUBsgmd4Y7P+ARraznLczrUZj/v8U5tz0IHl9clszNbKgftWFPFJit2LeFQ+afq7VUkySLfhNFCrFBcgbVct7q0dI/SyyiHx8ITYo+c4Sxuf+cOkCG3pa+5TbTdMojkxPmbWQxIUil38aVGvOTxrXD66WNgg1IHhkpVp14vF8jCPZoQHSb3RWcANIw6iDPI/Kd8r8SQpEQXm2ucYMJNLcYe3Z0WtT1CVRhq2BrVS5Wlv/eeINWhyjkHHnQArMZ0yjxe2UPxLXu8B3+zKoB1jZqqrtEZeJNPcEhKwAjRJ0jfc2lpR60dFBwAlaVOzYVtrFmZQ7QXQKjnP1Hq6mTP9zhwhQRGbQhHsjbfDUF+eF9UixevsBwt2n9DCI80RzfxcZKMWwZfJN6UrpAEBisKYT48uLu5VdSL1dZFVEaqYKsXvE/3fY9nUv9At9QrFVp1TbXP7IuUqmaq36ZDcf7zzLUzaTeutA==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-redis
      namespace: infisical
    type: Opaque
