---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-postgresql
  namespace: infisical
spec:
  encryptedData:
    password: AgCBcY8Jcm38uLiVutnttCEMAEWlMMA/ghpiIzm1oVIdAQc6ExWyVxDRTkdb18GuprVDAtv0Exzgua0s+K1O5Ux0oMstz9x+3zvo+oP5zMAP21F26CG3csEHlYoeF6CojtAZPIhCTLhHk1hG8Po9mG8R5sj3JZwKeOij8aSW2IbgrG83PRtud3UuyIky3jdG4+sC1ljzJBirgUXx7M4kr2Tm4dSEi9xx1IEoSWncqwd8H51/HOBrE9KgJnhC8xRnH7gJrgo5VxujxSXHzfgU8WaICNvQWnP/BcPyl8i/DH2dFxBAQJYtFXoA/aetvlBnTS3wXA9BhbHeGkdiViV7lnyx6CZO22tOdMQxmsYmaGlpjm/lQihdCk+kTc0a7VZ3hS0s82Lv6zL1scq1oqHiaX2BzmBj47Cr+Sw4Fs51aNT2tWykVgISudi59a3uDjTjldzBSal7D9QGQw5jC8h2MdJkE74/WL0bt7pYwAYSciKRGTAKdgCneBWh14DmvDnQxOPa/3upswq+Q9b7vyN+vjYlsyg7sMbVq6rrayYoraeyS3x/UVaXSp7DUlsPXX/d/KLvRIzHCh8bvGmP0zG5fc+AfEAzkFMIpsD2qn0qCwf4IOjRd98nuNonCyBs8CAxh6/FCmcodiYgOrq9w/D0HpoyDVNPBpYEuW+7COLkJp4AkK1HTPY5ZvKGLYI6DDrhh1iG9QjYCUKQFUG8PbADPdubMzPt+AVY4tLDxVnaYfDfWtrKymeMo9VKBMqTOQ==
    postgres-password: AgAeaKMdPJbwE07KHa6UoglFSoRk/LMSW9PHFn9FOt1kfIkm5WHWds2YixNwsilJ6v5z1v5JnT8kRNeytyNYQ42r0i4Oj55DRMO3zMje2Z8M1v9NOu90C0t3OlGQG21zd7R+5EEl7AtD5Lh5XX9WZQSXf9AsAnPr8s34Ut1mYXxwR7VQjyxpKqljv+BPAO+sGl5yEn5BO6Y2pkYR/0eLZGygpWott3KvxsSkfQSvZFHvpasQmHWZf5Oat5wlsdMhGDeNpcEU1P6vA8aYqCXPmSwUklCHgUH+P+XfGby/5kdAMMCuo5EuFVyQo3yLAPjZqWBBV3XlvSuUkdPd9QN39XB7boGmEyE/VtviuqTQwXN2HJ/VLGpicgJe/OdB+pa3cwda+jZsHM4V4g4aMReuvk/7mEvgvV+1chCTjBzbaH/3aue5fqJmn/yGMB9S976UYR2q+pGs/pYkgIfPW+OCKHbIhq5LsI7K8T9fxJ+sIMWyz9WxRDkyIcW7nqyTKYCmlqrPZ6Ea3RHhQox8wA7x0FNko1K/FfUIUfDkGF8rM6XXge6m3dNXl4TUUPz6VjRqLE2NMvHib68engnMKQDuVaMLQ/2cf6DGKTj0Yzqi+oMQ/HRfGtFvWANNztwTLqL+i4MulppOHcQpNiJylMubbKr3xN9PS0lNdJMl06ei9+QOTh54iELr2K8Xq1v65099ghiSyQMHxaSG6B0YYN5hTtYnSDc/evi1fKBH1rIGCcWmgmWw6EHcNnj/sQN21w==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-postgresql
      namespace: infisical
