---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: infisical-redis
  namespace: infisical
spec:
  encryptedData:
    redis-password: AgDIBRR/UiyAgUXyHNS8lEe3OiBdQa+HUICr3C93gMdM6tPKs0bBJLDMxrwU6b0xOjuvDmuN8xbCETOmTZ03U/4kJHvHk8U35yUykZLtzyq5WTdbXeK9bpM5tn+B9PSIvjzyMfHTOE1KrzZ4Jkycs9LerJVu1L5qObNohSZxm7cbYB+WqV+bFoSzElEE/GGDxU7SA7prc5vOF0JsReFZ7wC3en01UrJHIEnZklhwqU7OWhPsiwyI4LFWeFwsqGsPuMvKQVXeTasQxE73iG3pDR0i2uCfquaespHzOZiZDtD/N0EBrR4F0oDO2CtfC2Hv2BZS+dKH86KTASc7khbLeMxdTVKLd0eFQQ61P/JAuMIJ0wyPOSXvLTOn8OEZiVGdnzj6EwhUXzK1C0vNr7sRLH7pTmr1UpZl7WZZmJxl44+oa0T5t9ILYWvYXaoJbIyb9eph56PzU7A4oJzbR7iZRSUT4diyvE3pWrvFy+oAmwabQaIsRhfg7LnAsuewcBm4sQ1AT4XtZc/Hup4JGHkY+hZjIbCUGw2dqzPXaZTQUhmPIosFyyAlzytoeJn3hLE7xlA2HTeyRQE6e1TaZxisbbJbDSpcsjNN5xhMq7P7pMu1JbhAqhdnJ7UEzUaLU+B2X+WGD/3pKsSUhJUXow9vGJejw9UybJzYos1B0P5xht86Vhj8QjEu+y5E04M9megN5NDkD5nB1rpD2w/FjbtYp9jwM0Dqg3dOaKyumqfc5qJga5D/hP9SafQJrk+Aog==
  template:
    metadata:
      creationTimestamp: null
      name: infisical-redis
      namespace: infisical
